clone:
  depth: 1
pipelines:
  branches:
    main:
      - step:
          name: Testing
          caches: [node]
          image: cedxbelin/haxe.node
          script:
            - npm install
            - npm test
